title: TheRandomMelon
email: trm@melonz.nl
description: I make Discord bots and other kinds of software. May or may not be a literal melon.
baseurl: ""
url: https://therandommelon.xyz
urlnp: therandommelon.xyz
twitter: https://twitter.com/trmmelon
github: https://github.com/TheRandomMelon/blog
permalink: /blog/:year/:title
desc: I make Discord bots and other kinds of software. May or may not be a literal melon.

markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
